services:
  postgres:
    image: postgres:15-alpine
    container_name: smp4-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-smp4}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB:-smp4_db}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - smp4-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-smp4} -d ${POSTGRES_DB:-smp4_db}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: mehdimp4/smp4-vm-manager-backend:latest
    container_name: smp4-backend
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - /mnt/user/appdata/smp4-vm-manager/data:/data
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://${POSTGRES_USER:-smp4}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB:-smp4_db}?schema=public
      - JWT_SECRET=${JWT_SECRET}
      - PROXMOX_URL=${PROXMOX_URL}
      - PROXMOX_API_TOKEN=${PROXMOX_API_TOKEN}
      - PROXMOX_NODE=${PROXMOX_NODE}
      - LXC_SSH_PASSWORD=${LXC_SSH_PASSWORD}
      - BACKEND_IP=${BACKEND_IP}
      - CF_ACCOUNT_ID=${CF_ACCOUNT_ID}
      - CF_API_TOKEN=${CF_API_TOKEN}
      - CF_TUNNEL_ID=${CF_TUNNEL_ID}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_SECURE=${SMTP_SECURE}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - SMTP_FROM=${SMTP_FROM}
    ports:
      - "${BACKEND_PORT:-3000}:3000"
    networks:
      - smp4-net

  frontend:
    image: mehdimp4/smp4-vm-manager-frontend:latest
    container_name: smp4-frontend
    restart: unless-stopped
    ports:
      - "${APP_PORT:-8090}:80"
    depends_on:
      - backend
    networks:
      - smp4-net

  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: smp4-tunnel
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CF_TUNNEL_TOKEN}
    networks:
      - smp4-net

  vpn:
    image: mehdimp4/smp4-vm-manager-vpn:latest
    container_name: smp4-vpn
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    environment:
      - VPN_ENDPOINT=${VPN_ENDPOINT:-azeur-ptero-node.smp4.xyz:51821}
    volumes:
      - /lib/modules:/lib/modules
      - /mnt/user/appdata/smp4-vm-manager/wireguard:/etc/wireguard
    ports:
      - "51821:51821/udp"
    restart: unless-stopped
    networks:
      - smp4-net

  watchtower:
    image: containrrr/watchtower
    container_name: smp4-watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 --cleanup smp4-backend smp4-frontend smp4-vpn
    restart: unless-stopped

volumes:
  postgres-data:
  backend-data:


networks:
  smp4-net:
    driver: bridge
