services:
  backend:
    image: mehdimp4/smp4-vm-manager-backend:latest
    container_name: smp4-backend
    restart: unless-stopped
    volumes:
      - /mnt/user/appdata/smp4-vm-manager/data:/data
    command: /bin/sh -c "npx prisma migrate deploy && npm start"
    environment:
      - DATABASE_URL=file:/data/dev.db
      - JWT_SECRET=${JWT_SECRET}
      - PROXMOX_URL=${PROXMOX_URL}
      - PROXMOX_API_TOKEN=${PROXMOX_API_TOKEN}
      - PROXMOX_NODE=${PROXMOX_NODE}
      - LXC_SSH_PASSWORD=${LXC_SSH_PASSWORD}
      - BACKEND_IP=${BACKEND_IP}
    ports:
      - "${BACKEND_PORT:-3000}:3000"
    networks:
      - smp4-net

  frontend:
    image: mehdimp4/smp4-vm-manager-frontend:latest
    container_name: smp4-frontend
    restart: unless-stopped
    ports:
      - "${APP_PORT:-8090}:80"
    depends_on:
      - backend
    networks:
      - smp4-net

  watchtower:
    image: containrrr/watchtower
    container_name: smp4-watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 --cleanup smp4-backend smp4-frontend
    restart: unless-stopped

volumes:
  backend-data:


networks:
  smp4-net:
    driver: bridge
